services:
  webapp:
    container_name: shortlink_web_api
    build:
      context: .
      dockerfile: src/ShortLink.WebAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DOTNET_ENVIRONMENT=Development
    depends_on:
      postgres_db:
        condition: service_healthy
    
  postgres_db:
    container_name: db_postgres_container
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdlka
      POSTGRES_DB: short_link
    ports:  
      - "9090:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d short_link" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  postgres_data: